name: E2E Tests
on:
  push:
    branches:

      jobs:
        test:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v3
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '22.17.1'
            - name: Install dependencies
              run: npm install
            - name: Start dev server in background
              run: 
                npm run dev 
                & echo $! > .server_pid
            - name: Wait for server to be ready
              run: sleep 10
            - name: Run E2E tests
              run: npx playwright test e2e --headed
            - name: Stop dev server (only on success)
              if: ${{ success() }}
              run: |
                if [ -f .server_pid ]; then
                  kill $(cat .server_pid) || true
                  rm .server_pid
                fi
